version: 2

jobs:
  ci:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "0a:f1:27:85:56:44:07:44:50:60:40:8f:1f:73:b5:30" 

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Run linter
          command: npm run lint

      - run:
          name: Build SPA file
          command: npm run build
      
      - run:
          name: Deploy to server
          command: | 
            ssh-keyscan -H donpasquale.cs.unibo.it >> ~/.ssh/known_hosts
            scp -r dist/ matteo.vannucchi@donpasquale.cs.unibo.it:/home/web/site202120/html/public/frontend/dashboard

workflows:
  version: 2
  ci:
    jobs:
      - ci:
          filters:
            branches:
              only:
                - main
                - master
